### ISSUE TITLE
Prompt Container textarea and scrollbar design issues

### ISSUE THREAD

**Issue by prasannakarki77** [ahmadbilaldev/langui#10]
- The minimal prompt component's textarea seems to be resizable while the other types are not resizable. 

- I think instead of default design, it would be great if the scroll bar is customized to better suit the theme of the components. The send button overlaps the scroll bar slightly. 

- We can take reference from chat GPT's scroll bar and the prompt input. The max height of the prompt input can be same as 4 or 5 rows height and texts overflowing more than that can be scrolled.
# minimal
![image](https://github.com/ahmadbilaldev/langui/assets/63549402/4e513f42-242e-4a3f-a48a-cba23df7dd99)
![image](https://github.com/ahmadbilaldev/langui/assets/63549402/caa26820-0ef1-41bd-9d1a-6a7e1fa35bd5)

# other
![image](https://github.com/ahmadbilaldev/langui/assets/63549402/7d8fccfc-c8e4-49d9-a644-d17521eb6fa1)

I would like to contribute if possible.

**Comment by ahmadbilaldev** [comment]
Hi @prasannakarki77 , thank you for the suggestions. Agree with the first two points. 

> We can take reference from chat GPT's scroll bar and the prompt input. The max height of the prompt input can be same as 4 or 5 rows height and texts overflowing more than that can be scrolled.

Can we do this using only CSS? I think we may need JavaScript to implement an auto-resizable textarea, which is out of the scope of LangUI. 

Please feel free to contribute. Take a look at the `CONTRIBUTING` guide and let me know if you need any help. 😃

**Comment by prasannakarki77** [comment]
@ahmadbilaldev You are right, it isn't possible with just css. We cannot make it dynamic with content length. Either have to add more rows to the textarea upfront which is not necessarily good. 

Also, with the scroll bar design, I think the users have to set their own custom default scroll bar design to match with the component's as well as the global scrollbar. For lang ui you could set a global custom scroll bar design. I tried setting it globally, but it doesn't work for the preview, I don't know why. So, that's why I wanted to better know the project structure and code but ENOENT error occurred.

![image](https://github.com/ahmadbilaldev/langui/assets/63549402/5359363b-3e5b-4e8b-9219-e951366f687e)
![image](https://github.com/ahmadbilaldev/langui/assets/63549402/ae919689-73dc-4949-8223-0a20ab0e121e)

I am getting the following error and the components/styles don't load properly. The path is correct all files, folders exists. I can't seem to be able to figure out what might be the issue. I even tried reinstalling the packages multiple times.

error - Error: ENOENT: no such file or directory, open 'D:\Projects\Open Source\langui\src\data\categories\components.css.mdx'
digest: "1410947463"

![image](https://github.com/ahmadbilaldev/langui/assets/63549402/7c2f1caf-282b-4d85-b2d6-e5563eec7e21)

**Comment by ahmadbilaldev** [comment]
@prasannakarki77 You need to build the components by running the following command:

`npm run css:components` 

As explained in the [`CONTRIBUTING`](https://github.com/ahmadbilaldev/langui/blob/main/CONTRIBUTING.md) guide.

As far as the scrollbars go, a good UX and accessibility strategy is to never alter the scrollbars unless you absolutely have to.
