### ISSUE TITLE
Support for Themes?

### ISSUE THREAD

**Issue by pietz** [ahmadbilaldev/langui#15]
What's the recommended way of integrating a certain theme like company colors or logos?

**Comment by ahmadbilaldev** [comment]
Hi @pietz, For now LangUI has reusable standalone components so there is no theme support. However, it uses only two colors (slate and blue) and is very consistent in terms of primary and secondary colors. 

The best way about this is recognising the color and replacing it with your theme. For instance, blue-600 is consistently the active color in LangUI. Replace it with your theme's active color. I know it is manual but hope that helps.
