### ISSUE TITLE
How do I use langui in my Vue project?

### ISSUE THREAD

**Issue by wangrizhao** [ahmadbilaldev/langui#16]
I have reviewed the langui documentation, but I'm still unsure how to use it in my Vue project. Could you please provide some guidance? Thank you.

**Comment by a0m0rajab** [comment]
Hi, 

it's explained in the Getting Started: 

https://github.com/ahmadbilaldev/langui#get-started

> LangUI components are ready-to-use, meaning you don't need to install or configure anything.
> Browse [LangUI.dev](https://www.langui.dev/) and select a comopnent.
> Copy the desired component's code in HTML or JSX from the LangUI documentation.
> Paste the code into your project's HTML or React/Vue/Angular components. Done.

**Comment by injemamul** [comment]
Can you please make a blog post implementing in it in html

**Comment by ahmadbilaldev** [comment]
You will need a basic knowledge of html and css to implement it, every application is different so I will not be able to help you out with your specific use case unfortunately. It is just code that you can add into your vue app. Let me know if there is anything else I can help with.
